# -*- coding: utf-8 -*-
"""Basic-AI-Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YbXivFDUsF6PHdJorh1Ey-UXhNW4fZrl

## Dolly 3B Model - by Databricks
---
1. Model Name: Dolly-v2-3b
2. Model Parameters: 3 Billion
3. Training: Instruction-tuned Model
4. Link: https://huggingface.co/databricks/dolly-v2-3b
---
"""

# install dependencies
!pip install transformers
!pip install sentencepiece
!pip install accelerate

import torch                        # allows Tensor computation with strong GPU acceleration
from transformers import pipeline   # fast way to use pre-trained models for inference
import os

# load model
dolly_pipeline = pipeline(model="databricks/dolly-v2-3b",
                            torch_dtype=torch.bfloat16,
                            trust_remote_code=True,
                            device_map="auto")

# define helper function
def get_completion_dolly(input):
  system = f"""
  You are an expert in Content Marketing.
  You are good at explaining Content Marketing concepts in simple words.
  Help as much as you can.
  """
  #prompt = f"#### System: {system}\n#### User: \n{input}\n\n#### Response from Dolly-v2-3b:"
  prompt = f"#### User: \n{input}\n\n#### Response from Dolly-v2-3b:"
  print(prompt)
  dolly_response = dolly_pipeline(prompt,
                                  max_new_tokens=500
                                  )
  return dolly_response[0]["generated_text"]

# let's prompt
prompt = "Who is AIDA Marketing Strategy?"
# prompt = "Why is the Sky blue?"

print(get_completion_dolly(prompt))

"""### Build AI Physics Tutor"""

!pip install gradio

import locale
print(locale.getpreferredencoding())

locale.getpreferredencoding = lambda: "UTF-8"

# https://stackoverflow.com/questions/56081324/why-are-google-colab-shell-commands-not-working

import gradio as gr

# build an app front-end / ai tool with Gradio
iface = gr.Interface(fn=get_completion_dolly, inputs=[gr.Textbox(label="Insert Prompt Here",lines=6)],
                     outputs=[gr.Textbox(label="Your Answer Here",lines=3)],
                     title="The Fakeer Gpt (Under Development)",
                     examples=["Explain the difference between nuclear fusion and fission.",
                              "Why is the Sky blue?"]
                     )
iface.launch(share=True)

iface.close()